feat: Entrega a parte de Descrição de Dados da Exploração de Dados(#5)
atlantico-academy/risk-prediction pull request #8
Opened 2022-09-18 02:10 UTC by gabriellfelix

2022-09-19 16:38 UTC, omadson commented
Podem ir adicionando as mudanças nessas branch. Deixem o PR aberto. Quando estiverem com tudo pronto, irei avaliar e efetuar o merge.

2022-09-26 14:49 UTC, omadson requested changes
Algumas coisas podem ser feitas para melhorar:

![image](https://user-images.githubusercontent.com/1690232/192307435-fb35b579-e98f-4766-9ddf-956aee589bc1.png)

1. Teria como agrupar todos os `outros` em um só grupo?

![image](https://user-images.githubusercontent.com/1690232/192308047-15b025b5-a161-46de-89d4-dde26c0b92c6.png)

2. Ao final da análise, é interessante que se tenha um apurado de todos os _insights_ mais importantes da análise.

2022-09-30 21:39 UTC, marcelloale commented
> 1. Teria como agrupar todos os `outros` em um só grupo?
> 2. Ao final da análise, é interessante que se tenha um apurado de todos os insights mais importantes da análise.

Agrupei os valores unknown 0,5,6 ao 4 (outros) e no final coloquei os principais 4 insights que considerei mais interessante.

2022-10-05 00:38 UTC, omadson approved these changes

2022-10-05 00:38 UTC, merged